name: Build Natives
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: windows-latest
          vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - if: matrix.os == 'windows-latest'
        name: Find openssl
        run: Get-Command openssl
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Version Info
        run: mvn -version
      - if: matrix.os != 'windows-latest'
        name: OpenSSL Library Version Info
        run: openssl version -v
      - if: matrix.os == 'windows-latest'
        name: Install Full OpenSSL Library
        run: |
          Get-ChildItem "C:\Program Files\OpenSSL\bin"
          echo $Env:PATH
          Get-Command openssl
          $Env:PATH = "C:\Users\runneradmin\AppData\Local\vcpkg;C:\Users\runneradmin\AppData\Local\vcpkg\installed\x86-windows\tools\openssl;C:\vcpkg\packages\openssl_x64-windows\share\openssl;C:\Program Files\OpenSSL-Win64\bin;C:\Program Files\PowerShell\7;C:\hostedtoolcache\windows\jdk\11.0.17\x64\bin;C:\Program Files\MongoDB\Server\5.0\bin;C:\aliyun-cli;C:\vcpkg;C:\Program Files (x86)\NSIS\;C:\tools\zstd;C:\Program Files\Mercurial\;C:\hostedtoolcache\windows\stack\2.9.1\x64;C:\cabal\bin;C:\\ghcup\bin;C:\tools\ghc-9.4.2\bin;C:\Program Files\dotnet;C:\mysql\bin;C:\Program Files\R\R-4.2.2\bin\x64;C:\SeleniumWebDrivers\GeckoDriver;C:\Program Files (x86)\sbt\bin;C:\Program Files (x86)\GitHub CLI;C:\Program Files\Git\bin;C:\Program Files (x86)\pipx_bin;C:\npm\prefix;C:\hostedtoolcache\windows\go\1.17.13\x64\bin;C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts;C:\hostedtoolcache\windows\Python\3.9.13\x64;C:\hostedtoolcache\windows\Ruby\3.0.5\x64\bin;C:\tools\kotlinc\bin;C:\hostedtoolcache\windows\Java_Temurin-Hotspot_jdk\8.0.352-8\x64\bin;C:\Program Files\ImageMagick-7.1.0-Q16-HDRI;C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\wbin;C:\ProgramData\kind;C:\Program Files\Microsoft\jdk-11.0.12.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\dotnet\;C:\ProgramData\Chocolatey\bin;C:\Program Files\PowerShell\7\;C:\Program Files\Microsoft\Web Platform Installer\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Strawberry\c\bin;C:\Strawberry\perl\site\bin;C:\Strawberry\perl\bin;C:\ProgramData\chocolatey\lib\pulumi\tools\Pulumi\bin;C:\Program Files\TortoiseSVN\bin;C:\Program Files\CMake\bin;C:\ProgramData\chocolatey\lib\maven\apache-maven-3.8.6\bin;C:\Program Files\Microsoft Service Fabric\bin\Fabric\Fabric.Code;C:\Program Files\Microsoft SDKs\Service Fabric\Tools\ServiceFabricLocalClusterManager;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Program Files\GitHub CLI\;c:\tools\php;C:\Program Files (x86)\sbt\bin;C:\SeleniumWebDrivers\ChromeDriver\;C:\SeleniumWebDrivers\EdgeDriver\;C:\Program Files\Amazon\AWSCLIV2\;C:\Program Files\Amazon\SessionManagerPlugin\bin\;C:\Program Files\Amazon\AWSSAMCLI\bin\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\LLVM\bin;C:\Users\runneradmin\.dotnet\tools;C:\Users\runneradmin\.cargo\bin;C:\Users\runneradmin\AppData\Local\Microsoft\WindowsApps"
          echo $Env:PATH
          Get-Command openssl
          Get-ChildItem "C:\Program Files\OpenSSL\bin"
          openssl version -v
          openssl version
          choco uninstall openssl
          choco uninstall openssl.light
          vcpkg remove openssl --recurse
          vcpkg remove openssl.light --recurse
          vcpkg upgrade
          vcpkg install openssl:x64-windows
          vcpkg list openssl
          vcpkg upgrade --no-dry-run
          vcpkg integrate install          
          Get-ChildItem "C:\Users\runneradmin\AppData\Local\vcpkg"
          Get-ChildItem "C:\vcpkg\packages\"
          Get-ChildItem "C:\vcpkg\packages\openssl_x64-windows\share\openssl"
          Get-ChildItem "C:\vcpkg"
          Get-ChildItem "C:\Program Files\OpenSSL-Win64\bin"
          Get-ChildItem "C:\Program Files\OpenSSL-Win64"
          setx path "C:\Users\runneradmin\AppData\Local\vcpkg\installed\x86-windows\tools\openssl;C:\vcpkg\packages\openssl_x64-windows\share\openssl;C:\Program Files\OpenSSL-Win64\bin;%path%"
          openssl version -v
          openssl version
          vcpkg search openssl
          openssl version -v
          openssl version -v
      - if: matrix.os != 'windows-latest'
        name: Build with Maven
        env:
          path: C:\vcpkg\installed
        run: |
          openssl version -v
          mvn -B package --file pom.xml
      - if: matrix.os == 'windows-latest'
        name: Build with Microsoft Visual Studio native tools command prompt and Maven
        env:
          VCVARS: ${{ matrix.vcvars }}
        shell: cmd
        run: |
          call "%VCVARS%" x64
          mvn -B package --file pom.xml
      - if: ${{ github.event_name == 'push' }}
        name: Archive the built native artifacts if this is a tag
        uses: actions/upload-artifact@v2
        with:
          name: built-natives
          path: |
            **/target/**.jar
