name: Build Natives
on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: windows-latest
          vcvars: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - if: matrix.os == 'windows-latest'
        name: Find openssl
        run: where openssl
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Maven Version Info
        run: mvn -version
      - if: matrix.os != 'windows-latest'
        name: OpenSSL Library Version Info
        run: openssl version -v
      - if: matrix.os == 'windows-latest'
        name: Install Full OpenSSL Library
        run: |
          echo $Env:PATH
          $Env:PATH = "C:\Users\runneradmin\AppData\Local\vcpkg\installed\x86-windows\tools\openssl;C:\vcpkg\packages\openssl_x64-windows\share\openssl;C:\Program Files\OpenSSL-Win64\bin;$Env:PATH";
          echo $Env:PATH
          openssl version -v
          openssl version
          choco uninstall openssl
          choco uninstall openssl.light
          vcpkg remove openssl --recurse
          vcpkg remove openssl.light --recurse
          vcpkg upgrade
          vcpkg install openssl:x64-windows
          vcpkg list openssl
          vcpkg upgrade --no-dry-run
          vcpkg integrate install
          setx path "C:\Users\runneradmin\AppData\Local\vcpkg\installed\x86-windows\tools\openssl;C:\vcpkg\packages\openssl_x64-windows\share\openssl;C:\Program Files\OpenSSL-Win64\bin;%path%"
          set PATH="C:\Users\runneradmin\AppData\Local\vcpkg\installed\x86-windows\tools\openssl;C:\vcpkg\packages\openssl_x64-windows\share\openssl;C:\Program Files\OpenSSL-Win64\bin;$Env:PATH";
          echo $Env:PATH
          openssl version -v
          openssl version
          vcpkg search openssl
          openssl version -v
          openssl version -v
      - if: matrix.os != 'windows-latest'
        name: Build with Maven
        env:
          path: C:\vcpkg\installed
        run: |
          openssl version -v
          mvn -B package --file pom.xml
      - if: matrix.os == 'windows-latest'
        name: Build with Microsoft Visual Studio native tools command prompt and Maven
        env:
          VCVARS: ${{ matrix.vcvars }}
        shell: cmd
        run: |
          call "%VCVARS%" x64
          mvn -B package --file pom.xml
      - if: ${{ github.event_name == 'push' }}
        name: Archive the built native artifacts if this is a tag
        uses: actions/upload-artifact@v2
        with:
          name: built-natives
          path: |
            **/target/**.jar
